In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score,accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split

In [32]:
data=pd.read_csv('datasets/heart_attack.csv')
x=np.array(data.iloc[:,0:data.shape[1]-1])
np.set_printoptions(suppress=True,precision=2) # suppresses scientific notation into normal floating point notation
print(x)
y=data.iloc[:,data.shape[1]-1]
print(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [33]:
m1=LogisticRegression()
m1.fit(x_train,y_train)
m2=DecisionTreeClassifier()
m2.fit(x_train,y_train)
print('LR Accuracy : ',accuracy_score(y_test,m1.predict(x_test)))
print('DT Accuracy : ',accuracy_score(y_test,m2.predict(x_test)))

LR Accuracy :  0.9016393442622951
DT Accuracy :  0.8360655737704918


C:\Users\viral\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [34]:
print('LR confusion matrix : ',confusion_matrix(y_test,m1.predict(x_test)),sep='\n',end='\n\n')
print('DT confustion matrix : ',confusion_matrix(y_test,m2.predict(x_test)),sep='\n')

LR confusion matrix : 
[[26  6]
 [ 0 29]]

DT confustion matrix : 
[[24  8]
 [ 2 27]]


In [35]:
data=pd.read_csv('datasets/student_performance.csv')
x=np.array(data.iloc[:,:data.shape[1]-1])
y=np.array(data.iloc[:,data.shape[1]-1])
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x)
print(y)

[[1001.     17.      1.   ...    1.      0.      2.93]
 [1002.     18.      0.   ...    0.      0.      3.04]
 [1003.     15.      0.   ...    0.      0.      0.11]
 ...
 [3390.     16.      1.   ...    0.      1.      1.14]
 [3391.     16.      1.   ...    1.      0.      1.8 ]
 [3392.     16.      1.   ...    0.      1.      2.14]]
[2. 1. 4. ... 2. 1. 1.]


In [36]:
m2.fit(x_train,y_train)
confusion_matrix(y_test,m2.predict(x_test))

array([[ 16,   2,   1,   2,   2],
       [  1,  55,   1,   1,   3],
       [  2,   3,  89,   4,   2],
       [  1,   1,   4,  96,   0],
       [  2,   2,   2,   3, 303]])

Precision Recall and F1 scores

In [37]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [38]:
data=pd.read_csv('datasets/heart_attack.csv')
x=np.array(data.iloc[:,0:data.shape[1]-1])
np.set_printoptions(suppress=True,precision=2) # suppresses scientific notation into normal floating point notation
print(x)
y=data.iloc[:,data.shape[1]-1]
print(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [39]:
m2=DecisionTreeClassifier()
m2.fit(x_train,y_train)
print('DT confustion matrix : ',confusion_matrix(y_test,m2.predict(x_test)),sep='\n')

DT confustion matrix : 
[[24  8]
 [ 2 27]]


In [40]:
print('Precision score : ',precision_score(y_test,m2.predict(x_test)),precision_score(y_test,m2.predict(x_test),average=None))
print('Recall score : ',recall_score(y_test,m2.predict(x_test)),recall_score(y_test,m2.predict(x_test),average=None))
print('F1 score : ',f1_score(y_test,m2.predict(x_test)),f1_score(y_test,m2.predict(x_test),average=None))

Precision score :  0.7714285714285715 [0.92 0.77]
Recall score :  0.9310344827586207 [0.75 0.93]
F1 score :  0.84375 [0.83 0.84]


right is for 1 and left is for 0 , it returns for 1 in all the cases

In [41]:
data=pd.read_csv('datasets/student_performance.csv')
x=np.array(data.iloc[:,:data.shape[1]-1])
y=np.array(data.iloc[:,data.shape[1]-1])
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x)
print(y)

[[1001.     17.      1.   ...    1.      0.      2.93]
 [1002.     18.      0.   ...    0.      0.      3.04]
 [1003.     15.      0.   ...    0.      0.      0.11]
 ...
 [3390.     16.      1.   ...    0.      1.      1.14]
 [3391.     16.      1.   ...    1.      0.      1.8 ]
 [3392.     16.      1.   ...    0.      1.      2.14]]
[2. 1. 4. ... 2. 1. 1.]


In [42]:
m2.fit(x_train,y_train)
confusion_matrix(y_test,m2.predict(x_test))

array([[ 24,   1,   2,   0,   3],
       [  5,  66,   1,   3,   2],
       [  0,   3,  95,   2,   2],
       [  1,   4,   2, 100,   0],
       [  1,   4,   2,   4, 271]])

In [60]:
m2=DecisionTreeClassifier()
m2.fit(x_train,y_train)
confusion_matrix(y_test,m2.predict(x_test))

array([[ 24,   1,   1,   0,   4],
       [  4,  67,   2,   3,   1],
       [  0,   3,  95,   2,   2],
       [  3,   4,   2,  98,   0],
       [  1,   5,   2,   4, 270]])

In [59]:
print('Precision score : ',precision_score(y_test,m2.predict(x_test),average='macro'),precision_score(y_test,m2.predict(x_test),average=None))
print('Recall score : ',recall_score(y_test,m2.predict(x_test),average='macro'),recall_score(y_test,m2.predict(x_test),average=None))
print('F1 score : ',f1_score(y_test,m2.predict(x_test),average='macro'),f1_score(y_test,m2.predict(x_test),average=None))

Precision score :  0.9003662069971184 [0.86 0.84 0.93 0.91 0.97]
Recall score :  0.8969281999392067 [0.8  0.87 0.94 0.92 0.96]
F1 score :  0.8983739018720233 [0.83 0.85 0.94 0.91 0.96]


In [63]:
from sklearn.metrics import classification_report

In [65]:
print(classification_report(y_test,m2.predict(x_test)))

              precision    recall  f1-score   support

         0.0       0.75      0.80      0.77        30
         1.0       0.84      0.87      0.85        77
         2.0       0.93      0.93      0.93       102
         3.0       0.92      0.92      0.92       107
         4.0       0.97      0.96      0.97       282

    accuracy                           0.93       598
   macro avg       0.88      0.89      0.89       598
weighted avg       0.93      0.93      0.93       598

