In [102]:
import pandas as pd
import numpy as np
import seaborn as sns 
from sklearn.datasets import load_diabetes
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import random

In [119]:
x,y=load_diabetes(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [51]:
m1=SGDRegressor(max_iter=1000,learning_rate='constant',eta0=0.01)
m1.fit(x_train,y_train)
r2_score(y_test,m1.predict(x_test))

0.44527900062456527

In [52]:
m1.coef_

array([  49.36396187,  -75.46314702,  313.46790574,  257.44683589,
         29.90610307,  -12.70841016, -185.58812056,  149.48647911,
        320.13192793,  134.03120869])

In [53]:
m1.intercept_

array([151.10984823])

In [150]:
class my_MBGD:
    def __init__(self):
        self.lr=0.5
        self.epochs=400
        self.coef_=None
        self.intercept_=0
        self.b_size=100
    def fit(self,x,y):
        self.coef_=np.ones(x.shape[1])
        for i in range(self.epochs):
            for j in range(int(x.shape[0]/self.b_size)):
                idx=random.sample(range(x.shape[0]),self.b_size)
                y_bar=np.dot(x[idx],self.coef_)+self.intercept_
                slope_i=-2*np.mean(y[idx]-y_bar)
                slope_c=-2*np.dot((y[idx]-y_bar).T,x[idx])/x.shape[0]

                self.coef_=self.coef_-(self.lr*slope_c)
                self.intercept_=self.intercept_-(self.lr*slope_i)
        print(self.coef_,self.intercept_)
    def predict(self,x):
        return np.dot(x,self.coef_)+self.intercept_

In [151]:
m2=my_MBGD()
m2.fit(x_train,y_train)
r2_score(y_test,m2.predict(x_test))

[  49.22380643  -81.08450229  325.23867511  262.66039501   29.08867589
  -14.11623833 -189.46884698  151.40328161  328.48527341  133.02784563] 152.34232859898907


0.44838375213447645

MBGD inbuild

In [175]:
m3=SGDRegressor(learning_rate='constant',eta0=0.5)

In [176]:
batch_size=100

for i in range(500):
    idx=random.sample(range(x_train.shape[0]),batch_size)
    m3.partial_fit(x_train[idx],y_train[idx])

In [177]:
m3.coef_

array([  -3.47035875, -184.35965809,  424.94759277,  361.96776872,
       -145.69713515,  -24.20852808, -157.29520917,   67.77707648,
        512.44463911,  109.3412036 ])

In [178]:
m3.intercept_

array([133.75867661])

In [179]:
r2_score(y_test,m3.predict(x_test))

0.4472200208100463