In [11]:
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score

In [6]:
data=make_regression(n_samples=20,n_features=2,n_informative=2,n_targets=1,noise=20)

In [7]:
data

(array([[ 1.8139736 ,  0.53826281],
        [-0.75587555, -0.15743893],
        [ 0.03605798,  0.17430237],
        [-1.13119228,  0.34612032],
        [ 0.4236601 , -0.10206685],
        [ 0.10564295, -0.43331179],
        [ 1.07017686, -0.89616096],
        [-0.85376298,  1.48538387],
        [ 0.89310457, -0.88336149],
        [-0.55481975, -0.4458058 ],
        [-0.03635161, -0.06073926],
        [ 0.26819577, -0.2051636 ],
        [ 1.11472136, -1.07321683],
        [-0.67155137, -0.37921072],
        [-0.64228165,  0.16945307],
        [-1.24538435,  0.53758376],
        [-1.63062801,  0.07898761],
        [-1.12566884, -0.49886815],
        [-0.62582818,  0.14851967],
        [-0.12846181,  1.62834054]]),
 array([148.94618876, -47.49304333,  21.74856039, -20.54937323,
         25.8563119 , -31.08355925, -47.07542702,  91.76815828,
        -35.99150215, -69.88015429,  -1.2115259 , -35.7486239 ,
        -42.17078201, -84.40741593, -44.28731918, -40.2504942 ,
        -82.79750889, 

In [14]:
x=data[0]
y=data[1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [34]:
model=LinearRegression()
model.fit(x_train,y_train)
predicted=model.predict(x_test).flatten()

Second Time

In [15]:
data=load_diabetes(return_X_y=True)
x=data[0]
y=data[1]

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [17]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [18]:
r2=r2_score(y_test,model.predict(x_test))
r2

0.4399338661568969

In [19]:
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [20]:
model.intercept_

np.float64(151.88331005254167)

Making Own LR

In [25]:
class LR:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    def fit(self,x,y):
        x=np.insert(x,0,1,axis=1)
        betas=np.linalg.inv(np.dot(x.T,x)).dot(x.T).dot(y)
        self.intercept_=betas[0]
        self.coef_=betas[1:]
    def predict(self,x):
        val=x.dot(self.coef_)+self.intercept_
        return val

In [28]:
model=LR()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
r2=r2_score(y_test,y_pred)
r2

0.4399338661568968