In [1]:
import numpy as np
import pandas as pd

In [26]:
data=pd.read_csv('datasets/iris.csv',names=['col'+str(i) for i in range(1,4)]+['target'])
data.head()

,col1,col2,col3,target
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa


In [116]:
data.shape

(150, 5)

In [15]:
from sklearn.preprocessing import StandardScaler

In [30]:
ss=StandardScaler()
data=ss.fit_transform(np.array(data.iloc[:,:-1]).T)

In [76]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

In [77]:
data

array([[ 1.320,  1.279,  1.318,  1.265,  1.326,  1.315,  1.325,  1.294,
         1.268,  1.251,  1.315,  1.272,  1.265,  1.330,  1.368,  1.363,
         1.370,  1.331,  1.298,  1.331,  1.249,  1.336,  1.378,  1.279,
         1.198,  1.225,  1.298,  1.302,  1.313,  1.251,  1.239,  1.318,
         1.327,  1.352,  1.251,  1.336,  1.336,  1.251,  1.302,  1.294,
         1.347,  1.225,  1.318,  1.330,  1.270,  1.293,  1.305,  1.298,
         1.315,  1.306,  0.074,  0.109, -0.048, -0.209, -0.131, -0.051,
         0.079,  0.176, -0.025,  0.033, -0.162,  0.091, -0.162, -0.074,
         0.312,  0.109,  0.000,  0.079, -0.416,  0.000, -0.054,  0.091,
        -0.327, -0.070,  0.054,  0.054, -0.143, -0.172, -0.054,  0.226,
        -0.030,  0.030,  0.091, -0.297,  0.000,  0.195,  0.000, -0.284,
         0.174, -0.091, -0.102,  0.000,  0.000,  0.106, -0.028,  0.162,
         0.084,  0.054,  0.373,  0.058, -0.423, -0.392, -0.411, -0.334,
        -0.432, -0.463, -0.340, -0.400, -0.497, -0.310, -0.183, 

In [78]:
cov_matrix=np.cov(data)

In [79]:
cov_matrix

array([[ 0.525, -0.501, -0.023],
       [-0.501,  0.491,  0.010],
       [-0.023,  0.010,  0.013]])

In [80]:
eigvalues, eigvectors = np.linalg.eig(cov_matrix)

In [81]:
eigvalues

array([ 1.010, -0.000,  0.019])

In [82]:
eigvectors

array([[-0.719,  0.577, -0.387],
       [ 0.695,  0.577, -0.429],
       [ 0.024,  0.577,  0.816]])

In [85]:
pc1 = np.dot(data.T,eigvectors[0])
pc2 = np.dot(data.T,eigvectors[1])
pc3 = np.dot(data.T,eigvectors[2])

In [87]:
pc1,pc2,pc3

(array([-0.649, -0.536, -0.644, -0.500, -0.668, -0.636, -0.664, -0.575,
        -0.507, -0.467, -0.636, -0.520, -0.500, -0.681, -0.813, -0.795,
        -0.822, -0.683, -0.586, -0.685, -0.463, -0.700, -0.855, -0.536,
        -0.348, -0.406, -0.586, -0.597, -0.630, -0.467, -0.437, -0.644,
        -0.673, -0.755, -0.467, -0.700, -0.700, -0.467, -0.599, -0.575,
        -0.735, -0.406, -0.644, -0.681, -0.513, -0.573, -0.606, -0.586,
        -0.636, -0.609,  1.120,  1.090,  1.220,  1.339,  1.283,  1.222,
         1.116,  1.029,  1.202,  1.155,  1.306,  1.106,  1.306,  1.240,
         0.899,  1.090,  1.182,  1.116,  1.468,  1.182,  1.225,  1.106,
         1.416,  1.237,  1.137,  1.137,  1.292,  1.313,  1.225,  0.983,
         1.206,  1.157,  1.106,  1.397,  1.182,  1.012,  1.182,  1.389,
         1.031,  1.253,  1.261,  1.182,  1.182,  1.092,  1.204,  1.042,
         1.111,  1.137,  0.836,  1.133,  1.472,  1.454,  1.465,  1.420,
         1.477,  1.493,  1.423,  1.459,  1.511,  1.405,  1.321, 

## PCA

In [105]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [126]:
pca=PCA(n_components=3)

In [127]:
data=pd.read_csv('datasets/iris.csv',names=['col'+str(i) for i in range(1,5)]+['target'])

In [128]:
data.head()

,col1,col2,col3,col4,target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [129]:
X=np.array(data.iloc[:,:-1])
y=np.array(data.iloc[:,-1])

In [130]:
ss=StandardScaler()
X=ss.fit_transform(X)
X,y

(array([[-0.901,  1.032, -1.341, -1.313],
        [-1.143, -0.125, -1.341, -1.313],
        [-1.385,  0.338, -1.398, -1.313],
        [-1.507,  0.106, -1.284, -1.313],
        [-1.022,  1.263, -1.341, -1.313],
        [-0.537,  1.958, -1.171, -1.050],
        [-1.507,  0.801, -1.341, -1.182],
        [-1.022,  0.801, -1.284, -1.313],
        [-1.749, -0.356, -1.341, -1.313],
        [-1.143,  0.106, -1.284, -1.444],
        [-0.537,  1.495, -1.284, -1.313],
        [-1.264,  0.801, -1.228, -1.313],
        [-1.264, -0.125, -1.341, -1.444],
        [-1.870, -0.125, -1.512, -1.444],
        [-0.053,  2.189, -1.455, -1.313],
        [-0.174,  3.115, -1.284, -1.050],
        [-0.537,  1.958, -1.398, -1.050],
        [-0.901,  1.032, -1.341, -1.182],
        [-0.174,  1.726, -1.171, -1.182],
        [-0.901,  1.726, -1.284, -1.182],
        [-0.537,  0.801, -1.171, -1.313],
        [-0.901,  1.495, -1.284, -1.050],
        [-1.507,  1.263, -1.569, -1.313],
        [-0.901,  0.569, -1.171, -

In [131]:
X=pca.fit_transform(X)

In [132]:
X

array([[-2.265,  0.506,  0.122],
       [-2.086, -0.655,  0.227],
       [-2.368, -0.318, -0.051],
       [-2.304, -0.575, -0.099],
       [-2.389,  0.675, -0.021],
       [-2.071,  1.519, -0.031],
       [-2.446,  0.075, -0.342],
       [-2.234,  0.248,  0.083],
       [-2.342, -1.095, -0.154],
       [-2.189, -0.449,  0.247],
       [-2.163,  1.071,  0.264],
       [-2.327,  0.159, -0.100],
       [-2.224, -0.709,  0.223],
       [-2.640, -0.938, -0.190],
       [-2.192,  1.890,  0.469],
       [-2.251,  2.722, -0.033],
       [-2.203,  1.514,  0.001],
       [-2.190,  0.514,  0.039],
       [-1.894,  1.431,  0.371],
       [-2.340,  1.158, -0.137],
       [-1.915,  0.430,  0.416],
       [-2.205,  0.952, -0.165],
       [-2.774,  0.490, -0.339],
       [-1.820,  0.107, -0.040],
       [-2.228,  0.162, -0.124],
       [-1.957, -0.608,  0.299],
       [-2.052,  0.266, -0.092],
       [-2.168,  0.552,  0.201],
       [-2.140,  0.337,  0.265],
       [-2.269, -0.315, -0.076],
       [-2

In [133]:
from sklearn.preprocessing import LabelEncoder

In [134]:
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [135]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [138]:
from sklearn.neighbors import KNeighborsClassifier

In [139]:
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [140]:
from sklearn.metrics import accuracy_score

In [141]:
accuracy_score(y_test,knn.predict(X_test))

1.0

# Original Data

In [121]:
data=pd.read_csv('datasets/iris.csv',names=['col'+str(i) for i in range(1,5)]+['target'])

In [122]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=2)

In [124]:
knn2=KNeighborsClassifier(n_neighbors=4)
knn2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [125]:
accuracy_score(y_test,knn2.predict(X_test))

1.0